name: Check Debug Setting

on:
  pull_request:
    branches:
      - main

jobs:
  check_debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variable for GitHub Actions
        run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

      - name: Run Debug Check
        id: debug_check
        run: python check_debug_setting.py
        # If the script fails (non-zero exit status), stop the workflow and prevent merging.

      - name: Check Debug Script Result
        if: steps.debug_check.outputs.outcome != 'success'
        run: echo "Debug check passed. Proceeding with merging the pull request."
