name: Check Debug Setting

on:
  pull_request:
    branches:
      - main

jobs:
  check_debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Debug Check
<<<<<<< HEAD
        run: python check_debug_setting.py
=======
        run: python .github/check_debug_setting.py
        working-directory: .
        
      - name: Print DEBUG value
        run: |
          echo "DEBUG Value: ${{ env.DEBUG }}"
>>>>>>> 6c38a81b03ca6662bda437b4bdbde68f8438269f
